### ISSUE TITLE
Stolen code

### ISSUE THREAD

**Issue by Creeperface01** [WallMine/HARD-PORN#1]
Hi, i just want to warn you, that this code is stolen, and i suppose you probably didn't know about that so im sorry if you wanted to use it. But unfortunatelly you will have to remove it from github or any other public webside. **PS: jestli chcete dejte sem i mapky**

**Comment by majovec** [comment]
Hoziku česky pls jsem liny otevírat google traslator 🗡

**Comment by majovec** [comment]
A ten to kod nebyl ukradnut jelikož bohužel neumim nabourat se do tvého private repozitare do kterého mi dal kdysi davno Vítek pristup a za druhé nezapomen to napsat i k Tajne myska věci tak je core

**Comment by majovec** [comment]
a pokud si o tom chces vazne promluvit  nnpis na fb

**Comment by Creeperface01** [comment]
Říkám něco o nabourani? Platí to co jsem řekl, jestli nemáš dostatečný skill v angličtině a chceš něco vysvětlit stačí napsat. Core mi je jedno, ten je v podstatě na nic.

**Comment by majovec** [comment]
byt tebou to neresim nebo zde nahraju i ty nukkit pluginy :D které bezi na tom nukkitu co mas na svém profilu co editujes to mam vyzkousene 🗡

**Comment by Creeperface01** [comment]
Proč by sis předělával práci? A jako mě to je v podstatě jedno jako stejně to smažeš obojí že akorát tobě to zabere čas na víc ne mě

**Comment by Creeperface01** [comment]
A jako java pluginy to je úplně to samé co s těmihle tím si nijak nepomůžeš patří stejně mě jako tyto no

**Comment by majovec** [comment]
n nez to smzu takto vse uplotnu :) jink core a anni uz ma kalikod gamak a ragnok a pak další rusaku 🗡

**Comment by majovec** [comment]
a ja za to nemohu ze si nevedel komu davat pristup do private repozitare zvany mietox zaloha nebo aspoň se to tak drive jmenovalo

**Comment by Creeperface01** [comment]
Však říkám tobě to zabere čas navíc. Tak teoreticky ono to mít můžeš že dokud to volně nesiris, to jako nikdo ti počítač prohledávat nebude ani jim.

**Comment by Creeperface01** [comment]
Ale já chci ochránit kidy jako jsi ty a plno dalších před problémy tak proto to radši nepublikuji vůbec

**Comment by majovec** [comment]
a kdybych byl zmrd tak zrovna napisu Pocketmine Annihilation a mělo by to vetsi nastvnost tak to si to nasel pouze ty :)

**Comment by majovec** [comment]
a jasny kid co je starsi nez ty :D

**Comment by Creeperface01** [comment]
Však říkám že jako ty jim akorát děláš problémy no.

**Comment by majovec** [comment]
ok no tak to zde smazu a hodim jen link na muj google drive tak že v pripade problemu si zaloz new topic nazdar

**Comment by Creeperface01** [comment]
No jo záleží jak to bereš, ale podle věku soudí málo kdo. Respektive podle věku můžeš odhadnout. Ale ne přesně, v tomto případě vůbec.

**Comment by majovec** [comment]
a  blbost ze ste tam emeli drive licenci :D

**Comment by majovec** [comment]
tak uz to ma i ondraczsk :D

**Comment by Creeperface01** [comment]
Twl čti si ty komentáře, chápeš že mě to nevadí že to mají, ale pokud si to dají na server tak oni zbytečně utratí peníze ne já.

**Comment by Creeperface01** [comment]
BTW mapy jsou veřejné

**Comment by Creeperface01** [comment]
a ne nemusíš mi upravovat komentáře, to je dobrý, chápu že jinak by to nikdo o tobě nenapsal tak že potřebuješ trošku si zvýšit EGO ale jako jestli chceš, znám i jiné způsoby.

**Comment by majovec** [comment]
Nepotřebuji jelikož kdyby si vylezl na moje EGO a skocil si znej tak nikdy nedopadnes na zem :D

**Comment by majovec** [comment]
hmm zajimave to budes reportovat cca 12 serveru chces ip na ty ruske ? kde uz mají funkcni anni ? jebat sezen si to sam :D

**Comment by Creeperface01** [comment]
Tim pádem, jenom potvrzujes své IQ

**Comment by Creeperface01** [comment]
No a? Jejich problém.

**Comment by majovec** [comment]
Kamo ty jsi  dost komickej :D

**Comment by majovec** [comment]
stejnak by to byla jen otázka nej by to Ondřej zverejnil :D

**Comment by majovec** [comment]
jinak zajimave ze si zde na githubu nenasel ten repozitar kde Vitek zverejnil uplnou zalohu

**Comment by Creeperface01** [comment]
Ty jsi spíš trapný, nevím o co ti jde, ať zverejnis cokoliv z těch pluginu, tak jsou pořád moje. Kradení programů atd je tu odjakživa. A jako řeší se to vždycky stejně. Pokud ho používáš jen pro sebe tak to v podstatě nikdo neřeší ale když ho máš někde volně, tak ano po čase.

**Comment by Creeperface01** [comment]
A hlavně jako když ho nějaký kid bude mít, stejně to bude jenom trapná kopie. Takže to nikoho zajímat nebude.

**Comment by Creeperface01** [comment]
A servery s 1 hráčem neřeším..

**Comment by majovec** [comment]
no tak muzes to resit maximalne tim ze to officialne gidhub smaze jinak ne a jestli myslis STB tak se to resi az když je to  nad 5 tisíc jinak ne coz to není nikde to nemas znalcem potvrzene a jesli jop posli mi kopii kde to jasne pise.

**Comment by majovec** [comment]
no a tech ruských kde jsem to dal tak dnes tam bylo jen 89 rusaku tak ze uspesnost něco jako tvůj GayTeam ještě nejake otázky ?

**Comment by Creeperface01** [comment]
Jak nad 5 000? A já jsem se na nic neptal.

**Comment by majovec** [comment]
jelikož nad 5k to je trestni cin a jinak prestupek a navíc ty to nemuzes nijak resit když si v te době tam nemel ani licenci :D

**Comment by Creeperface01** [comment]
Když o tom nic nevíš, tak nic neříkej.... Já sice taky nejsem znalec ale zřejmě víc nez ty..

**Comment by Creeperface01** [comment]
Na private nemusim mít licenci to vypovídá samo za sebe

**Comment by majovec** [comment]
nerekl bych jelikož asi nemas rejstrik tak pestry jak ja :D a toto není chat jestli se chces o tom stae byvit tak jak uz jsem před tim psal napis mi na fb ten mas :D

**Comment by Creeperface01** [comment]
Já se nepotřebuji o ničem bavit, všechno jsem ti už řekl.

**Comment by majovec** [comment]
a ja ti na vse odpověděl :)

**Comment by majovec** [comment]
jinak btw necham to na Gamakoj a kalikodoj zda toto smažou ale ja to nebudu ja budu stále nahravat :D

**Comment by Creeperface01** [comment]
Myslím že 2 lidi s deltou IQ 50 nemůžou vést rozumný rozhovor (a aby sis to špatně nevylozil tak já jsem na té horní hranici.)

**Comment by majovec** [comment]
jedine když spis :D

**Comment by Creeperface01** [comment]
Nevím o tom že by se IQ měnilo při spaní, a jestli ano tak jedině dolů, takže tím pádem by normálně byl rozdíl větší než 50, to byl jenom typ takže jestli se necítíš na tolik tak možná že to může být 60 nebo 70

**Comment by majovec** [comment]
joo ted si mi to nadal v plne parade :D

**Comment by Creeperface01** [comment]
Nejspíš ti to nepřijde ale tvé výroky o tom svědčí.. na nemyslnou větu ti odpovím podobně

**Comment by Creeperface01** [comment]
A jakože nandal sis to sám. Ale zřejmě sis to neuvědomil tak jsem ti to trošku pretlumocil

**Comment by majovec** [comment]
a asi tí nedoslo že tve keci mam tezce v prdeli  a rikam toto není chat

**Comment by Creeperface01** [comment]
No zřejmě ne když furt, sice nesmyslně, na mě reagujes

**Comment by majovec** [comment]
mam rad když mam osledni slovo :D

**Comment by majovec** [comment]
jinak doufam ze te ty krami brzy prejdou  protože vysilujes jak trinacka co ma poprvé krami :D

**Comment by Creeperface01** [comment]
Za to tebe to zřejmě nepřejde v 19 nebo kolika je velmi malá šance takže tvůj vývoj zřejmě už skončil což je smutné, protože zřejmě brzo.

**Comment by majovec** [comment]
Ano pamet mas jjeste dobro ze se pamatuješ muj vek ale nezapomen za mesic rikat ze mi je 20 :D

**Comment by Creeperface01** [comment]
Taky se divím že si pamatuju věci o někom jako jsi ty. Ale to nic nemění na tom co jsem psal.

**Comment by GamakCZ** [comment]
Honzo, nechci ti do toho kecat, ale nejsme jediní kdo používají tvé kódy.

**Comment by Creeperface01** [comment]
Tak samozřejmě že je taky používám

**Comment by GamakCZ** [comment]
Nemyslim tebe :/

**Comment by Creeperface01** [comment]
Tak to je jedno že to používají nějací kidi. A stejně bez anticheatu jim to je na nic

**Comment by majovec** [comment]
Honziku ty si dost fandis když obejt se da vse

**Comment by majovec** [comment]
jinak Gamku na finecraftu brzy bude anni :D

**Comment by GamakCZ** [comment]
Aha, jsme nevěděl že květináč je kid :D....

**Comment by GamakCZ** [comment]
a jaká je ip

**Comment by majovec** [comment]
gamaku ip nwm ja vim jen to ze jsem to borisoj dal a asi to hodim i na critalix rusaci budou radi

**Comment by Creeperface01** [comment]
Už víš. Nedá se vše

**Comment by majovec** [comment]
nebudu ti tu predstavu brat ale da se se divim ze si ještě zdena githubu nenasel celou zalohu když uz ji videlo 16 lidi

**Comment by Creeperface01** [comment]
Taky jsem přemýšlel že bych udělal zvlášť anni server bez anticheatu pro hackery ale když to uděláte za mě tak nemusím aspoň plýtvat servery.

**Comment by majovec** [comment]
jinak šikmookej monty to vi ze tu jsou zverejneny tve pluginy ?

**Comment by majovec** [comment]
akorad se snazim prijit k cemu dobremu je gthttpapi to je na ty expy ne ?

**Comment by Creeperface01** [comment]
Nevím zeptej se ho

**Comment by Creeperface01** [comment]
No to je obecně na všechno.

**Comment by majovec** [comment]
jinak musim uznat mas zajimave delane nukkit pluginy ze když je dekompiluji a pak zase kompiluji tak pak nejdou nacist tak ze jak magor musim editovat class aby to fakalo :D

**Comment by Creeperface01** [comment]
Zřejmě je dekompilujes špatně. Java se většinou nedekompiluje

**Comment by majovec** [comment]
to ano ano ale ja za to nemohu ze funkcni core byl jen ten v jaru a na tam te si netroufnu jelikož se javu ucim teprve

**Comment by majovec** [comment]
a navíc i ten co je jen ve slozkach tak ani FdevTools ho echce nacist tak ze mi nic jiného nezbyva

**Comment by majovec** [comment]
a dále ti musim podekovat za ten tvůj pocketmine na 0.14 ten tvůj imagicalmie co tam mas diky nemu sem si vzal cody aby bezlo bw :D

**Comment by Creeperface01** [comment]
Vůbec nevím co myslíš

**Comment by majovec** [comment]
jak v te zaloze je slozka src tak to je preci ten tvůj imagical mine co si mel drive na serveru a znej sem si vzal  par  codu aby běželo bw jak ma jelikož pocketmine se od tech casu dost zmenil 🗡
